include("FunField/DegreeLocalization.jl")
include("FunField/Factor.jl")
include("FunField/HessQR.jl")
include("FunField/IntClsZx.jl")
include("FunField/Divisor.jl")
include("FunField/Divisor2.jl")
include("FunField/Differential.jl")
include("FunField/Prime.jl")
